### ISSUE TITLE
Keyboard shortcut events do not trigger on swingeducation

### ISSUE THREAD

**Issue by pevner-p2** [ProdPerfect/prodperfect-keen-tracking.js#27]
Swingeducation (react app)  substitute teacher onboarding flow has (and encourages use of) keyboard shortcuts. 

These shortcuts are not being recorded. 

[production](subs.swingeducation.com)  (snippet installed)

[staging](http://dev.swingeducation.com) (snippet not installed) 

To reproduce: 
on [dev.swingeducation.com](dev.swingeducation.coml) log in with the following: 
username:  swingeducation-user+sub@prodperfect.com
pass:  Hello123!

Choose "substitute teach" 

You are now on a form on [http://dev.swingeducation.com/#/sub/onboard-form](http://dev.swingeducation.com/#/sub/onboard-form)

This encourages the use of keyboard shortcuts (enter, tab) to navigate the system, but these events are not tracked.

On _other_  applications, these events are tracked. 

I'm guessing this is just a somewhat custom setup with their react setup.  In case it's universal for react apps, we should know and determine priority of recording these events with react.    

**NOTE** please do not finish the onboarding workflow for now, as it would require me to create more accounts.

Reference: [slack convo](https://prodperfect.slack.com/conversation/CCRHTJVQA/p1538055350000100)

Originally added: 28 Sep 2018

**Comment by funkhouserw** [comment]
Covered by #29 , removing
